var data = [
    {
        "appointmentId": "9714799259",
        "make": "Volkswagen",
        "model": "Golf",
        "year": "2018",
        "variant": "GTI",
        "trim": null,
        "specs": "GCC",
        "engineSize": 2.0,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": true,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "lowMileage",
            "label": "Low Mileage",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714799259/POST_REFURB/1629813645597/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 1451,
            "downPayment": 18140,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 90704.0,
        "mediaSource": "spincar",
        "price": 90704.0,
        "odometerReading": 47045,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714797661",
        "make": "Toyota",
        "model": "Rav 4",
        "year": "2016",
        "variant": "VX",
        "trim": null,
        "specs": "GCC",
        "engineSize": 2.5,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 3,401 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714797661/POST_REFURB/1629806138587/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 1056,
            "downPayment": 13199,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 3401,
        "targetPrice": 69400.0,
        "mediaSource": "spincar",
        "price": 65999.0,
        "odometerReading": 65814,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714803913",
        "make": "Toyota",
        "model": "Land Cruiser Prado",
        "year": "2017",
        "variant": "VXR",
        "trim": null,
        "specs": "GCC",
        "engineSize": 4.0,
        "noOfCylinders": "6",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 7,721 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714803913/POST_REFURB/1629814993866/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 1856,
            "downPayment": 23204,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 7721,
        "targetPrice": 123741.0,
        "mediaSource": "spincar",
        "price": 116020.0,
        "odometerReading": 80209,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714801844",
        "make": "Honda",
        "model": "Accord",
        "year": "2017",
        "variant": "2.4",
        "trim": null,
        "specs": "GCC",
        "engineSize": 2.4,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": null,
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714801844/POST_REFURB/1629815509684/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 920,
            "downPayment": 11504,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 57522.0,
        "mediaSource": "spincar",
        "price": 57522.0,
        "odometerReading": 111445,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714798479",
        "make": "Toyota",
        "model": "Yaris",
        "year": "2019",
        "variant": "SE",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.3,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 2,367 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714798479/POST_REFURB/1629814674079/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 663,
            "downPayment": 8287,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 2367,
        "targetPrice": 43803.0,
        "mediaSource": "spincar",
        "price": 41436.0,
        "odometerReading": 19305,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714800785",
        "make": "Mitsubishi",
        "model": "Lancer Ex",
        "year": "2017",
        "variant": "EX GLS",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.8,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "lighteningDeals",
            "label": "Lightning deals",
            "secondaryLabel": "AED 4,252 OFF"
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714800785/POST_REFURB/1629816364069/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 457,
            "downPayment": 5712,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 4252,
        "targetPrice": 32814.0,
        "mediaSource": "spincar",
        "price": 28562.0,
        "odometerReading": 69947,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714804320",
        "make": "Jeep",
        "model": "Wrangler",
        "year": "2017",
        "variant": "UNLIMITED",
        "trim": null,
        "specs": "GCC",
        "engineSize": 3.6,
        "noOfCylinders": "6",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": null,
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714804320/POST_REFURB/1629814269823/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 1533,
            "downPayment": 19158,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 95791.0,
        "mediaSource": "spincar",
        "price": 95791.0,
        "odometerReading": 103995,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714801929",
        "make": "Honda",
        "model": "Accord",
        "year": "2017",
        "variant": "LXB",
        "trim": null,
        "specs": "GCC",
        "engineSize": 2.4,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 2,554 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714801929/POST_REFURB/1630076323917/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 973,
            "downPayment": 12157,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 2554,
        "targetPrice": 63343.0,
        "mediaSource": "spincar",
        "price": 60789.0,
        "odometerReading": 92420,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714803944",
        "make": "Nissan",
        "model": "Altima",
        "year": "2018",
        "variant": "S",
        "trim": null,
        "specs": "GCC",
        "engineSize": 2.5,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 2,086 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714803944/POST_REFURB/1630076407542/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 681,
            "downPayment": 8509,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 2086,
        "targetPrice": 44632.0,
        "mediaSource": "spincar",
        "price": 42546.0,
        "odometerReading": 107267,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714799244",
        "make": "Toyota",
        "model": "Prado",
        "year": "2019",
        "variant": "GXR",
        "trim": null,
        "specs": "GCC",
        "engineSize": 4.0,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 7,153 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714799244/POST_REFURB/1629815801889/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 2023,
            "downPayment": 25290,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 7153,
        "targetPrice": 133603.0,
        "mediaSource": "spincar",
        "price": 126450.0,
        "odometerReading": 49429,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714798476",
        "make": "Toyota",
        "model": "Yaris",
        "year": "2019",
        "variant": "SE",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.3,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "lowMileage",
            "label": "Low Mileage",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714798476/POST_REFURB/1629814719321/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 663,
            "downPayment": 8287,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 41435.0,
        "mediaSource": "spincar",
        "price": 41435.0,
        "odometerReading": 15704,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714806655",
        "make": "Toyota",
        "model": "Yaris",
        "year": "2019",
        "variant": "SE",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.5,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": null,
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714806655/POST_REFURB/1629815983948/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 647,
            "downPayment": 8081,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 41718.0,
        "mediaSource": "spincar",
        "price": 40408.0,
        "odometerReading": 49449,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714805993",
        "make": "Mitsubishi",
        "model": "Montero",
        "year": "2016",
        "variant": "GLX",
        "trim": null,
        "specs": "GCC",
        "engineSize": 3.0,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "lowMileage",
            "label": "Low Mileage",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714805993/POST_REFURB/1629815859020/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 862,
            "downPayment": 10773,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 55157.0,
        "mediaSource": "spincar",
        "price": 53866.0,
        "odometerReading": 80004,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714800633",
        "make": "Toyota",
        "model": "Yaris",
        "year": "2019",
        "variant": "SE",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.5,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": null,
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714800633/POST_REFURB/1629815733393/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 621,
            "downPayment": 7754,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 40026.0,
        "mediaSource": "spincar",
        "price": 38770.0,
        "odometerReading": 72863,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714799312",
        "make": "Nissan",
        "model": "Sentra",
        "year": "2017",
        "variant": "SV",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.6,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 2,311 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714799312/POST_REFURB/1631618298705/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 881,
            "downPayment": 11005,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 2311,
        "targetPrice": 57336.0,
        "mediaSource": "spincar",
        "price": 55025.0,
        "odometerReading": 71155,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714800539",
        "make": "Renault",
        "model": "Captur",
        "year": "2019",
        "variant": "1.6",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.6,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "lowMileage",
            "label": "Low Mileage",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714800539/POST_REFURB/1629815251133/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 574,
            "downPayment": 7167,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 35836.0,
        "mediaSource": "spincar",
        "price": 35836.0,
        "odometerReading": 22023,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "1190629727",
        "make": "Toyota",
        "model": "Corolla",
        "year": "2018",
        "variant": "SE",
        "trim": null,
        "specs": "GCC",
        "engineSize": 2.0,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "lighteningDeals",
            "label": "Lightning deals",
            "secondaryLabel": "AED 5,087 OFF"
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_1190629727/POST_REFURB/1629811477329/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 639,
            "downPayment": 7980,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 5087,
        "targetPrice": 44987.0,
        "mediaSource": "spincar",
        "price": 39900.0,
        "odometerReading": 101592,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714806221",
        "make": "Toyota",
        "model": "Corolla",
        "year": "2020",
        "variant": "1.6 XLI",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.6,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": null,
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714806221/POST_REFURB/1629815911428/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 888,
            "downPayment": 11092,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 56790.0,
        "mediaSource": "spincar",
        "price": 55461.0,
        "odometerReading": 30607,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714800109",
        "make": "Mazda",
        "model": "CX 3",
        "year": "2018",
        "variant": "GS",
        "trim": null,
        "specs": "GCC",
        "engineSize": 2.0,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 2,276 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714800109/POST_REFURB/1629815850923/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 743,
            "downPayment": 9285,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 2276,
        "targetPrice": 48705.0,
        "mediaSource": "spincar",
        "price": 46429.0,
        "odometerReading": 119540,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714799889",
        "make": "Infiniti",
        "model": "Q70",
        "year": "2015",
        "variant": "3.7",
        "trim": null,
        "specs": "GCC",
        "engineSize": 3.7,
        "noOfCylinders": "6",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "lowMileage",
            "label": "Low Mileage",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714799889/POST_REFURB/1629813664832/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 928,
            "downPayment": 11603,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 58019.0,
        "mediaSource": "spincar",
        "price": 58019.0,
        "odometerReading": 93634,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714798467",
        "make": "Toyota",
        "model": "YARIS",
        "year": "2019",
        "variant": "SE",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1500.0,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 2,367 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714798467/POST_REFURB/1634026870487/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 663,
            "downPayment": 8287,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 2367,
        "targetPrice": 43803.0,
        "mediaSource": "spincar",
        "price": 41436.0,
        "odometerReading": 23224,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714799619",
        "make": "Mitsubishi",
        "model": "Lancer",
        "year": "2017",
        "variant": "EX",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.6,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 1,650 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714799619/POST_REFURB/1629816913014/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 488,
            "downPayment": 6224,
            "roi": 3.5,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 1650,
        "targetPrice": 32774.0,
        "mediaSource": "spincar",
        "price": 31124.0,
        "odometerReading": 99495,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714806158",
        "make": "Toyota",
        "model": "Fortuner",
        "year": "2018",
        "variant": "EXR 2.7 L",
        "trim": null,
        "specs": "GCC",
        "engineSize": 2.7,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": null,
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714806158/POST_REFURB/1629816741421/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 1291,
            "downPayment": 16140,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 83029.0,
        "mediaSource": "spincar",
        "price": 80703.0,
        "odometerReading": 97810,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714806800",
        "make": "Kia",
        "model": "Optima",
        "year": "2019",
        "variant": "2",
        "trim": null,
        "specs": "GCC",
        "engineSize": 2.0,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": null,
        "mainImage": {
            "path": "inspection-car/appointments/spincar/qa/AE/AE_CAR_9714806800/POST_REFURB/1629815185731/cu-2.jpg",
            "label": "RIGHT FRONT DIAGONAL (45-DEGREE) VIEW"
        },
        "emiDetails": {
            "emi": 838,
            "downPayment": 10474,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": false,
        "discountAmount": 0,
        "targetPrice": 53832.0,
        "mediaSource": "spincar",
        "price": 52372.0,
        "odometerReading": 86440,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    },
    {
        "appointmentId": "9714804142",
        "make": "Mazda",
        "model": "3",
        "year": "2016",
        "variant": "S",
        "trim": null,
        "specs": "GCC",
        "engineSize": 1.6,
        "noOfCylinders": "4",
        "turbochargerSuperchargerAvailable": false,
        "booked": false,
        "listingActive": true,
        "city": "Dubai",
        "cityCode": "DU_DUBAI",
        "salesLever": {
            "key": "discountedCars",
            "label": "AED 4,876 OFF",
            "secondaryLabel": null
        },
        "mainImage": {
            "path": "hello-ar/dev/uploads/4eeefe44-7573-491f-97af-6f309c074a24/c32eb188-5f47-4fa5-9b3d-82fee6b9b713/52.jpg",
            "label": "Front Left",
            "category": "Thumbnails"
        },
        "emiDetails": {
            "emi": 720,
            "downPayment": 9000,
            "roi": 3.99,
            "tenure": 60
        },
        "discounted": true,
        "discountAmount": 4876,
        "targetPrice": 49876.0,
        "mediaSource": "helloAR",
        "price": 45000.0,
        "odometerReading": 46746,
        "ownerNumber": null,
        "transmissionType": "Automatic",
        "fuelType": "Petrol"
    }
];

export default data;